### ISSUE TITLE
runtime error with curand.PRNG

### ISSUE THREAD

**Issue by shadowleaves** [ContinuumIO/numbapro-spca#2]
getting the following error at line 232:

Traceback (most recent call last):
  File "spca.py", line 412, in <module>
    main()
  File "spca.py", line 408, in main
    check_result()
  File "spca.py", line 337, in check_result
    gpu_opt_x = spca(Vd, d=dit, k=kit)
  File "spca.py", line 232, in spca_full
    prng = curand.PRNG(stream=custr)
  File "C:\Anaconda\lib\site-packages\numba\cuda\cudadrv\devices.py", line 137, in _r
equire_cuda_context
    return fn(_args, *_kws)
  File "C:\aroot\stage\Lib\site-packages\numbapro\cudalib\curand\api.py", line 75, in
 __init__
  File "C:\aroot\stage\Lib\site-packages\numbapro\cudalib\curand\api.py", line 30, in
 stream
  File "C:\aroot\stage\Lib\site-packages\numbapro\cudalib\curand\binding.py", line 22
3, in set_stream
  File "C:\aroot\stage\Lib\site-packages\numbapro\cudalib\libutils.py", line 41, in w
rapped
TypeError: this function takes 1 argument (2 given)

looks like it's complaining that PRNG was given argument (stream)?

**Comment by shadowleaves** [comment]
if it change line 232 to prng = curand.PRNG(), i get:

spca.py:313: RuntimeWarning: divide by zero encountered in true_divide
  opt_x[Ik] = (aIk / val)
These should be close: [[ 1.26679993]] [[ nan]]

**Comment by sklam** [comment]
Can you tell me what python and numbapro version you are using?

I have been developing this with:

cudatoolkit               6.0                          p0
llvm                      3.3                           0
llvmpy                    0.12.7                   py34_0
numba                     0.15.1               np19py34_0
numbapro                  0.16.0              np19py34_p0
numbapro_cudalib          0.1                           0
numpy                     1.9.0                    py34_0
python                    3.4.2                         0
